// Mocks generated by Mockito 5.4.6 from annotations
// in new_words/test/providers/memories_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:new_words/common/foundation/foundation.dart' as _i5;
import 'package:new_words/entities/word_explanation.dart' as _i4;
import 'package:new_words/services/memories_service_v2.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MemoriesServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoriesServiceV2 extends _i1.Mock implements _i3.MemoriesServiceV2 {
  MockMemoriesServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<List<_i4.WordExplanation>> getSpacedRepetitionWords() =>
      (super.noSuchMethod(
            Invocation.method(#getSpacedRepetitionWords, []),
            returnValue: _i2.Future<List<_i4.WordExplanation>>.value(
              <_i4.WordExplanation>[],
            ),
          )
          as _i2.Future<List<_i4.WordExplanation>>);

  @override
  _i2.Future<List<_i4.WordExplanation>> getWordsFromDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getWordsFromDate, [date]),
            returnValue: _i2.Future<List<_i4.WordExplanation>>.value(
              <_i4.WordExplanation>[],
            ),
          )
          as _i2.Future<List<_i4.WordExplanation>>);

  @override
  T processResponse<T>(_i5.ApiResponseV2<T>? response) =>
      (super.noSuchMethod(
            Invocation.method(#processResponse, [response]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#processResponse, [response]),
            ),
          )
          as T);

  @override
  void processVoidResponse(_i5.ApiResponseV2<void>? response) =>
      super.noSuchMethod(
        Invocation.method(#processVoidResponse, [response]),
        returnValueForMissingStub: null,
      );

  @override
  T processResponseWithCustomError<T>(
    _i5.ApiResponseV2<T>? response,
    _i5.ServiceException Function(String?, int?, int?)? errorFactory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processResponseWithCustomError, [
              response,
              errorFactory,
            ]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#processResponseWithCustomError, [
                response,
                errorFactory,
              ]),
            ),
          )
          as T);

  @override
  _i2.Future<T> safeApiCall<T>(_i2.Future<_i5.ApiResponseV2<T>>? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#safeApiCall, [apiCall]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#safeApiCall, [apiCall]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#safeApiCall, [apiCall]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<void> safeVoidApiCall(
    _i2.Future<_i5.ApiResponseV2<void>>? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeVoidApiCall, [apiCall]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  R transformData<T, R>(
    T? data,
    R Function(T)? transformer, {
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformData,
              [data, transformer],
              {#operationName: operationName},
            ),
            returnValue: _i6.dummyValue<R>(
              this,
              Invocation.method(
                #transformData,
                [data, transformer],
                {#operationName: operationName},
              ),
            ),
          )
          as R);

  @override
  void validateInput(Map<String, dynamic>? validations) => super.noSuchMethod(
    Invocation.method(#validateInput, [validations]),
    returnValueForMissingStub: null,
  );

  @override
  void validateStringField(
    String? value,
    String? fieldName, {
    int? minLength,
    int? maxLength,
    bool? required = true,
    Pattern? pattern,
    String? patternDescription,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateStringField,
      [value, fieldName],
      {
        #minLength: minLength,
        #maxLength: maxLength,
        #required: required,
        #pattern: pattern,
        #patternDescription: patternDescription,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateNumericField(
    num? value,
    String? fieldName, {
    num? min,
    num? max,
    bool? required = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateNumericField,
      [value, fieldName],
      {#min: min, #max: max, #required: required},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> processPaginationParams(
    int? pageNumber,
    int? pageSize, {
    int? maxPageSize = 100,
    int? minPageSize = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPaginationParams,
              [pageNumber, pageSize],
              {#maxPageSize: maxPageSize, #minPageSize: minPageSize},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String createErrorMessage(String? operation, String? details) =>
      (super.noSuchMethod(
            Invocation.method(#createErrorMessage, [operation, details]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createErrorMessage, [operation, details]),
            ),
          )
          as String);

  @override
  void logOperation(String? operation, {Map<String, dynamic>? parameters}) =>
      super.noSuchMethod(
        Invocation.method(
          #logOperation,
          [operation],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError(String? operation, _i5.ServiceException? error) =>
      super.noSuchMethod(
        Invocation.method(#logError, [operation, error]),
        returnValueForMissingStub: null,
      );
}
