arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart # Use default filename
output-dir: lib/generated # Specify output directory explicitly
output-class: AppLocalizations