// Mocks generated by Mockito 5.4.6 from annotations
// in new_words/test/services/memories_service_v2_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:new_words/apis/vocabulary_api_v2.dart' as _i4;
import 'package:new_words/common/foundation/foundation.dart' as _i2;
import 'package:new_words/entities/add_word_request.dart' as _i7;
import 'package:new_words/entities/page_data.dart' as _i8;
import 'package:new_words/entities/word_explanation.dart' as _i6;
import 'package:new_words/utils/app_logger_interface.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponseV2_0<T> extends _i1.SmartFake
    implements _i2.ApiResponseV2<T> {
  _FakeApiResponseV2_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOptions_1 extends _i1.SmartFake implements _i3.Options {
  _FakeOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VocabularyApiV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockVocabularyApiV2 extends _i1.Mock implements _i4.VocabularyApiV2 {
  MockVocabularyApiV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>> addWord(
    _i7.AddWordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWord, [request]),
            returnValue:
                _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>>.value(
                  _FakeApiResponseV2_0<_i6.WordExplanation>(
                    this,
                    Invocation.method(#addWord, [request]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>>);

  @override
  _i5.Future<_i2.ApiResponseV2<_i8.PageData<_i6.WordExplanation>>> listWords(
    int? pageNumber,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listWords, [pageNumber, pageSize]),
            returnValue: _i5.Future<
              _i2.ApiResponseV2<_i8.PageData<_i6.WordExplanation>>
            >.value(
              _FakeApiResponseV2_0<_i8.PageData<_i6.WordExplanation>>(
                this,
                Invocation.method(#listWords, [pageNumber, pageSize]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<_i8.PageData<_i6.WordExplanation>>>);

  @override
  _i5.Future<_i2.ApiResponseV2<void>> deleteWord(int? wordId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWord, [wordId]),
            returnValue: _i5.Future<_i2.ApiResponseV2<void>>.value(
              _FakeApiResponseV2_0<void>(
                this,
                Invocation.method(#deleteWord, [wordId]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<void>>);

  @override
  _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>> refreshExplanation(
    int? explanationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshExplanation, [explanationId]),
            returnValue:
                _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>>.value(
                  _FakeApiResponseV2_0<_i6.WordExplanation>(
                    this,
                    Invocation.method(#refreshExplanation, [explanationId]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponseV2<_i6.WordExplanation>>);

  @override
  _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>> getMemories(
    String? localTimezone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMemories, [localTimezone]),
            returnValue:
                _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>>.value(
                  _FakeApiResponseV2_0<List<_i6.WordExplanation>>(
                    this,
                    Invocation.method(#getMemories, [localTimezone]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>>);

  @override
  _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>> getMemoriesOnDate(
    String? localTimezone,
    String? yyyyMMdd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMemoriesOnDate, [localTimezone, yyyyMMdd]),
            returnValue:
                _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>>.value(
                  _FakeApiResponseV2_0<List<_i6.WordExplanation>>(
                    this,
                    Invocation.method(#getMemoriesOnDate, [
                      localTimezone,
                      yyyyMMdd,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResponseV2<List<_i6.WordExplanation>>>);

  @override
  void validateInput(Map<String, dynamic>? validations) => super.noSuchMethod(
    Invocation.method(#validateInput, [validations]),
    returnValueForMissingStub: null,
  );

  @override
  void validateStringField(
    String? value,
    String? fieldName, {
    int? minLength,
    int? maxLength,
    bool? required = true,
    Pattern? pattern,
    String? patternDescription,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateStringField,
      [value, fieldName],
      {
        #minLength: minLength,
        #maxLength: maxLength,
        #required: required,
        #pattern: pattern,
        #patternDescription: patternDescription,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateNumericField(
    num? value,
    String? fieldName, {
    num? min,
    num? max,
    bool? required = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateNumericField,
      [value, fieldName],
      {#min: min, #max: max, #required: required},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> processPaginationParams(
    int? pageNumber,
    int? pageSize, {
    int? maxPageSize = 100,
    int? minPageSize = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPaginationParams,
              [pageNumber, pageSize],
              {#maxPageSize: maxPageSize, #minPageSize: minPageSize},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<_i2.ApiResponseV2<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #fromJson: fromJson,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponseV2<T>>.value(
              _FakeApiResponseV2_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #fromJson: fromJson,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<T>>);

  @override
  _i5.Future<_i2.ApiResponseV2<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #fromJson: fromJson,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponseV2<T>>.value(
              _FakeApiResponseV2_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #fromJson: fromJson,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<T>>);

  @override
  _i5.Future<_i2.ApiResponseV2<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #fromJson: fromJson,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponseV2<T>>.value(
              _FakeApiResponseV2_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #fromJson: fromJson,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<T>>);

  @override
  _i5.Future<_i2.ApiResponseV2<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #fromJson: fromJson,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponseV2<T>>.value(
              _FakeApiResponseV2_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #fromJson: fromJson,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<T>>);

  @override
  _i5.Future<_i2.ApiResponseV2<void>> requestVoid(
    String? method,
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestVoid,
              [method, path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponseV2<void>>.value(
              _FakeApiResponseV2_0<void>(
                this,
                Invocation.method(
                  #requestVoid,
                  [method, path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponseV2<void>>);

  @override
  _i2.ApiResponseV2<T> parseResponse<T>(
    _i3.Response<dynamic>? response,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseResponse, [response, fromJson]),
            returnValue: _FakeApiResponseV2_0<T>(
              this,
              Invocation.method(#parseResponse, [response, fromJson]),
            ),
          )
          as _i2.ApiResponseV2<T>);

  @override
  _i2.ApiResponseV2<void> parseVoidResponse(_i3.Response<dynamic>? response) =>
      (super.noSuchMethod(
            Invocation.method(#parseVoidResponse, [response]),
            returnValue: _FakeApiResponseV2_0<void>(
              this,
              Invocation.method(#parseVoidResponse, [response]),
            ),
          )
          as _i2.ApiResponseV2<void>);

  @override
  _i3.Options createOptions({
    Duration? connectTimeout,
    Duration? receiveTimeout,
    Map<String, dynamic>? headers,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOptions, [], {
              #connectTimeout: connectTimeout,
              #receiveTimeout: receiveTimeout,
              #headers: headers,
              #contentType: contentType,
            }),
            returnValue: _FakeOptions_1(
              this,
              Invocation.method(#createOptions, [], {
                #connectTimeout: connectTimeout,
                #receiveTimeout: receiveTimeout,
                #headers: headers,
                #contentType: contentType,
              }),
            ),
          )
          as _i3.Options);

  @override
  _i3.Options createAnonymousOptions({
    Duration? connectTimeout,
    Duration? receiveTimeout,
    Map<String, dynamic>? headers,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousOptions, [], {
              #connectTimeout: connectTimeout,
              #receiveTimeout: receiveTimeout,
              #headers: headers,
              #contentType: contentType,
            }),
            returnValue: _FakeOptions_1(
              this,
              Invocation.method(#createAnonymousOptions, [], {
                #connectTimeout: connectTimeout,
                #receiveTimeout: receiveTimeout,
                #headers: headers,
                #contentType: contentType,
              }),
            ),
          )
          as _i3.Options);

  @override
  _i3.Options createLongRunningOptions({
    Duration? connectTimeout = const Duration(minutes: 2),
    Duration? receiveTimeout = const Duration(minutes: 5),
    Map<String, dynamic>? headers,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLongRunningOptions, [], {
              #connectTimeout: connectTimeout,
              #receiveTimeout: receiveTimeout,
              #headers: headers,
              #contentType: contentType,
            }),
            returnValue: _FakeOptions_1(
              this,
              Invocation.method(#createLongRunningOptions, [], {
                #connectTimeout: connectTimeout,
                #receiveTimeout: receiveTimeout,
                #headers: headers,
                #contentType: contentType,
              }),
            ),
          )
          as _i3.Options);
}

/// A class which mocks [AppLoggerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLoggerInterface extends _i1.Mock
    implements _i9.AppLoggerInterface {
  MockAppLoggerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void i(String? message) => super.noSuchMethod(
    Invocation.method(#i, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void d(String? message) => super.noSuchMethod(
    Invocation.method(#d, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void e(String? message) => super.noSuchMethod(
    Invocation.method(#e, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
