import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:new_words/entities/word_explanation.dart';
import 'package:new_words/features/add_word/presentation/add_word_dialog.dart';
// import 'package:url_launcher/url_launcher.dart'; // For opening links in markdown, if needed

class WordDetailScreen extends StatelessWidget {
  final WordExplanation wordExplanation;

  const WordDetailScreen({super.key, required this.wordExplanation});

  static const routeName = '/word-detail'; // Example route name

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        title: Text(wordExplanation.wordText),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Divider(),
            MarkdownBody(
              data: wordExplanation.markdownExplanation,
              selectable: true,
              // onTapLink: (text, href, title) { // Optional: handle link taps
              //   if (href != null) {
              //     launchUrl(Uri.parse(href));
              //   }
              // },
            ),
            const Divider(),
            Text(
              'Generated by: ${wordExplanation.providerModelName}',
              style: const TextStyle(fontSize: 12, color: Colors.grey),
            ),
            // Optionally display other fields like pronunciation, definitions, examples
            // if (wordExplanation.pronunciation != null) ...[],
            // if (wordExplanation.definitions != null) ...[],
            // if (wordExplanation.examples != null) ...[],
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async => AddWordDialog.show(context, replacePage: true),
        tooltip: 'Add New Word',
        child: const Icon(Icons.add),
      ),
    );
  }
}