name: Android CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'
          channel: 'stable'

      - name: Get version
        id: get_version
        run: |
          VERSION="dev-$(git rev-parse --short HEAD)-$(date '+%Y%m%d-%H%M%S')"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        run: |
          cp .env.production .env
          VERSION="${{ steps.get_version.outputs.version }}"
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/" .env
          flutter pub get
          flutter build apk --release

      - name: Rename APK
        run: |
          APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          VERSION="${{ steps.get_version.outputs.version }}"
          mv "$APK_PATH" "build/app/outputs/flutter-apk/newwords-$VERSION.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newwords-${{ steps.get_version.outputs.version }}
          path: build/app/outputs/flutter-apk/newwords-*.apk
          retention-days: 30
